spring.application.name=equipment-maintenance-control

spring.datasource.url=jdbc:mysql://localhost:3306/equipment-maintenance-control
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
email.provider.sender=equipment.maintenance.control@web2ufpr.me
email.provider.api-key=${RESEND_API_KEY}
